name: 'GitHub Actions Weather Bot'

on:
  push:
  schedule:
    - cron: '0 22 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: 'Get Weather'
        run: bash ./weather.sh
      - name: 'Get Date'
        run: echo "REPORT_DATE=$(TZ=':Asia/Shenyang' date '+%Y-%m-%d %T')" >> $GITHUB_ENV
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.163.com
          server_port: 465
          username: zhichuv@163.com
          password: TDSEESCYARUMQAMR
          subject: 沈阳天气预报 (${{env.REPORT_DATE}})
          body: 每天六点把天气预报发送给您
          html_body: file://result.html
          to: yc_zzh@qq.com   #,zhaochuanmin0129@163.com
          from: Lovely Baby
          ignore_cert: true
          convert_markdown: true


