name: 'GitHub Actions Weather Bot'

on:
  push:
  schedule:
    - cron: '0 22 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: 'Get Weather'
        run: bash ./weather.sh
      - name: 'Get Date'
        run: echo "REPORT_DATE=$(TZ=':Asia/Shenyang' date '+%Y-%m-%d %T')" >> $GITHUB_ENV
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.163.com
          server_port: 465
          username: zhichuv@163.com
          password: TDSEESCYARUMQAMR
          subject: Shenyang Weather Report (${{env.REPORT_DATE}})
          body: file://result.txt
          to: yc_zzh@qq.com
          from: GitHub Actions
          content_type: text/text

